version: '2'
services:

  ##########################
  ### MAIN FRONTEND #######
  ##########################

  fe_main:
    image: node:8.2-alpine
    environment:
      VIRTUAL_HOST: main.flc.local
    depends_on:
      - api_bus
    ports:
      - "3001:3000"
    volumes:
     - ./frontend-main:/app
    working_dir: /app
    command: yarn run start:dev

  ##########################
  ### GIFTS FRONTEND #######
  ##########################

  fe_gifts:
    image: node:8.2-alpine
    environment:
      VIRTUAL_HOST: gifts.flc.local
    depends_on:
      - api_bus
    ports:
      - "3000:3000"
    volumes:
     - ./frontend-gifts:/app
    working_dir: /app
    command: ['npm', 'start']

  ##########################
  ####### API BUS ##########
  ##########################

  api_bus:
    image: webdevops/php-nginx:alpine-3-php7
    depends_on:
      - be_gifts_nginx
      - be_donations_nginx
    environment:
      WEB_ALIAS_DOMAIN: api.flc.local
      WEB_DOCUMENT_ROOT: /app/public
      VIRTUAL_HOST: api.flc.local
    volumes:
      - ./backend-api-bus:/app
    working_dir: /app

  ##########################
  ### GIFTS BACKEND ########
  ##########################

  be_gifts:
    image: wodby/drupal-php:7.1-2.0.0
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost
      PHP_DOCROOT: web
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_AUTOSTART: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./backend-gifts:/var/www/html
      # - d4d-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

  be_gifts_mariadb:
    image: wodby/mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./backend-gifts/mysql/init:/docker-entrypoint-initdb.d
      - ./backend-gifts/mysql/data:/var/lib/mysql

  be_gifts_nginx:
    image: wodby/drupal-nginx:1.10-1.1.0
    depends_on:
      - be_gifts
      - be_gifts_mariadb
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: be_gifts
      NGINX_DOCROOT: web
      DRUPAL_VERSION: 8
      VIRTUAL_HOST: gifts.api.flc.local
    volumes_from:
      - be_gifts

  be_gifts_pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: be_gifts_mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"


  ##########################
  ### DONATIONS BACKEND ####
  ##########################

  be_donations:
    image: wodby/drupal-php:7.1
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost
      PHP_DOCROOT: web
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_AUTOSTART: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./backend-donations:/var/www/html
      #- d4d-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

  be_donations_mariadb:
    image: wodby/mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./backend-donations/mysql/init:/docker-entrypoint-initdb.d
      - ./backend-donations/mysql/data:/var/lib/mysql

  be_donations_nginx:
    image: wodby/drupal-nginx:1.10-1.1.0
    depends_on:
      - be_donations
      - be_donations_mariadb
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: be_donations
      NGINX_DOCROOT: web
      DRUPAL_VERSION: 8
      VIRTUAL_HOST: donations.api.flc.local
    volumes_from:
      - be_donations

  be_donations_pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: be_donations_mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8002:80"


  ##########################
  ### PHANTOM JS  ##########
  ##########################

  phantomjs:
    image: rosenhouse/phantomjs2:latest
    ports:
        - 8910
    entrypoint: phantomjs
    command: "--webdriver=8910"


  ##########################
  ### NGINX PROXY ##########
  ##########################
  # todo: fix replacement cw2 to flc.
  cw2_nginx_proxy:
    image: jwilder/nginx-proxy:0.5.0
    container_name: flc-nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  #########################
  ### MAILHOG #############
  ########################

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
