version: 2

jobs:
  build:
    docker:
      - image: wodby/wodby-cli:0.1.0-beta

    working_directory: /home/wodby/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - be-donations-composer-v1-{{ checksum "backend-donations/composer.lock" }}
            - be-donations-composer-v1-
      - save_cache:
          key: be-donations-composer-v1-{{ checksum "backend-donations/composer.lock" }}
          paths:
            - backend-donations/vendor

      - restore_cache:
          keys:
            - be-gifts-composer-v1-{{ checksum "backend-gifts/composer.lock" }}
            - be-gifts-composer-v1-
      - save_cache:
          key: be-gifts-composer-v1-{{ checksum "backend-gifts/composer.lock" }}
          paths:
            - backend-gifts/vendor

      - restore_cache:
          keys:
            - be-api-bus-composer-v1-{{ checksum "backend-api-bus/composer.lock" }}
            - be-api-bus-composer-v1-
      - save_cache:
          key: be-api-bus-composer-v1-{{ checksum "backend-api-bus/composer.lock" }}
          paths:
            - backend-api-bus/vendor

      - restore_cache:
          keys:
            - main-npm-v1-{{ checksum "frontend-main/package.json" }}
            - main-npm-v1-
      - save_cache:
          key: main-npm-v1-{{ checksum "frontend-main/package.json" }}
          paths:
            - frontend-main/node_modules

      - restore_cache:
          keys:
            - be-gifts-npm-v1-{{ checksum "frontend-gifts/package.json" }}
            - be-gifts-npm-v1-
      - save_cache:
          key: be-gifts-npm-v1-{{ checksum "frontend-gifts/package.json" }}
          paths:
            - frontend-gifts/node_modules

      - setup_remote_docker:
          docker_layer_caching: true

      - run: wodby ci init 107e26da-2b83-4594-b25a-f2d6027daa22
      # fix permissions
      - run: wodby ci run -u root -s be-donations-php -- chown -R wodby:wodby backend-*
      - run: wodby ci run -u root -s fe-main -- chown -R node:node frontend-*
      # install composer deps
      - run: wodby ci run -s be-donations-php -p backend-donations -- composer install --prefer-dist -n
      - run: wodby ci run -s be-gifts-php -p backend-gifts -- composer install --prefer-dist -n
      - run: wodby ci run -s be-api-bus-php -p backend-api-bus -- composer install --prefer-dist -n
      # install node deps
      - run: wodby ci run -s fe-main -p frontend-main -- yarn install
      - run: wodby ci run -s fe-gifts -p frontend-gifts -- yarn install
      # build images
      - run: wodby ci build be-donations- --from backend-donations
      - run: wodby ci build be-gifts- --from backend-gifts
      - run: wodby ci build be-api-bus- --from backend-api-bus
      - run: wodby ci build fe-main --from frontend-main
      - run: wodby ci build fe-gifts --from frontend-gifts
      # release and deploy
      - run: wodby ci release be- fe-
      - run: wodby ci deploy be- fe-
