version: 2

jobs:
  build:
    machine: true

    steps:
      - checkout

      - restore_cache:
          keys:
            - be-donationscomposer-v1-{{ checksum "composer.lock" }}
            - be-donationscomposer-v1-
      - save_cache:
          key: be-donationscomposer-v1-{{ checksum "backend-donations/composer.lock" }}
          paths:
            - backend-donations/vendor

      - restore_cache:
          keys:
            - be-gifts-composer-v1-{{ checksum "composer.lock" }}
            - be-gifts-composer-v1-
      - save_cache:
          key: be-gifts-composer-v1-{{ checksum "backend-gifts/composer.lock" }}
          paths:
            - backend-gifts/vendor

      - restore_cache:
          keys:
            - be-api-bus-composer-v1-{{ checksum "composer.lock" }}
            - be-api-bus-composer-v1-
      - save_cache:
          key: be-api-bus-composer-v1-{{ checksum "backend-api-bus/composer.lock" }}
          paths:
            - backend-api-bus/vendor

      - restore_cache:
          keys:
            - main-npm-v1-{{ checksum "package.json" }}
            - main-npm-v1-
      - save_cache:
          key: main-npm-v1-{{ checksum "frontend-main/package.json" }}
          paths:
            - frontend-main/node_modules

      - restore_cache:
          keys:
            - be-gifts-npm-v1-{{ checksum "package.json" }}
            - be-gifts-npm-v1-
      - save_cache:
          key: be-gifts-npm-v1-{{ checksum "frontend-gifts/package.json" }}
          paths:
            - frontend-gifts/node_modules

      - run: wget -qO- https://api.chingis.proxy.wodby.com/api/v1/get/cli | sh
      - run: wodby ci init 928acdc2-4c03-43ca-b34f-d00bdc45869f
      - run: wodby ci run be-donations-php -- composer install --prefer-dist --no-interaction -d backend-donations
      - run: wodby ci run be-gifts-php -- composer install --prefer-dist --no-interaction -d backend-gifts
      - run: wodby ci run be-api-bus-php -- composer install --prefer-dist --no-interaction -d backend-api-bus
      - run: wodby ci run fe-main -- yarn install --modules-folder frontend-main
      - run: wodby ci run fe-gifts -- yarn install --modules-folder frontend-gifts
      - run: wodby ci build be-donations-php --from backend-donations
      - run: wodby ci build be-gifts-php --from backend-gifts
      - run: wodby ci build be-api-bus-php --from backend-api-bus
      - run: wodby ci build fe-main --from frontend-main
      - run: wodby ci build fe-gifts --from frontend-gifts
      - run: wodby ci release be-donations-php be-gifts-php be-api-bus-php fe-main fe-gifts
      - run: wodby ci deploy be-donations-php be-gifts-php be-api-bus-php fe-main fe-gifts
