cw_gifts_cards.gift_card_config_type.*:
  type: config_entity
  label: 'Gifts Card Configuration type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
