# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of donations app. Must be unique within a project.
name: 'backend-api-bus'

# The runtime the application uses.
type: 'php:7.1'

# Configuration of the build of this application.
build:
    flavor: composer

relationships:
    be_donations: 'backend-donations:http'
    be_gifts: 'backend-gifts:http'

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'public'

            # How long to allow static assets from this location to be cached.
            #
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
            # 365 days).
            expires: 5m

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            #
            # Can be true, false or a URI path string.
            passthru: '/index.php'

            # Deny access to static files in this location.
            allow: false

# The size of the persistent disk of the application (in MB).
disk: 256

mounts:
    '/logs': 'shared:files/backend-api-bus-logs'
